services:
  web:
    image: nginx
    volumes:
      - './docker/nginx/config.conf:/etc/nginx/conf.d/default.conf'
      - './main:/var/www'
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      - php-nginx2
  php:
    build:
      context: ./docker/php
    container_name: my_phpfpm
    volumes:
      - './main:/var/www'
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - php-nginx2
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
     - './docker/storage/mysql:/var/lib/mysql'
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: qwe123
     MYSQL_DATABASE: mydb
     MYSQL_USER: myuser
     MYSQL_PASSWORD: mypassword
     MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - '3306:3306'
    networks:
    - php-nginx2
    command: --default-authentication-plugin=mysql_native_password
networks:
  php-nginx2:
    driver: bridge